### ISSUE TITLE
Panic on enemy kill to level up

### ISSUE THREAD

**Issue by Bombadad** [Brian-Catcow-B/dungeon-raid-core#1]
Killing enemy and assuming to lvl up got the following error:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /home/caleb/.cargo/git/checkouts/dungeon-raid-core-525e90c5fb56e476/f26b170/src/game/improvement_choices.rs:109:34
                                                                note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: `improvement_choices.rs`
Line: `109`

**Comment by Bombadad** [comment]
Update: when I was leveling up the `Bounty` ability and a health I got this same error on `space`. Maybe throw a log of game state or rework to have an error as a return?

**Comment by Brian-Catcow-B** [comment]
fixed in latest core change. Thanks for the line number :D
